# -*- coding: utf-8 -*-
"""OT_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PQTb2zaNWR7sOnqMj_tdZIn6OY8mSVax
"""

!pip install numpy matplotlib
!python tsp_all_algorithms.py

import numpy as np
import random
import matplotlib.pyplot as plt

# -----------------------------
# Generate Cities
# -----------------------------
NUM_CITIES = 15
np.random.seed(42)
cities = np.random.rand(NUM_CITIES, 2) * 100

def distance(a, b):
    return np.linalg.norm(a - b)

def total_distance(route):
    return sum(distance(cities[route[i]], cities[route[(i+1)%NUM_CITIES]])
               for i in range(NUM_CITIES))

# -----------------------------
# GENETIC ALGORITHM
# -----------------------------
def genetic_algorithm():
    pop_size = 30
    generations = 50
    mutation_rate = 0.02

    def create_route():
        return list(np.random.permutation(NUM_CITIES))

    def crossover(p1, p2):
        start, end = sorted(random.sample(range(NUM_CITIES), 2))
        child = [-1]*NUM_CITIES
        child[start:end] = p1[start:end]
        ptr = 0
        for gene in p2:
            if gene not in child:
                while child[ptr] != -1:
                    ptr += 1
                child[ptr] = gene
        return child

    def mutate(route):
        if random.random() < mutation_rate:
            i, j = random.sample(range(NUM_CITIES), 2)
            route[i], route[j] = route[j], route[i]

    population = [create_route() for _ in range(pop_size)]

    for _ in range(generations):
        population.sort(key=total_distance)
        new_pop = population[:2]  # elitism

        while len(new_pop) < pop_size:
            p1, p2 = random.sample(population[:10], 2)
            child = crossover(p1, p2)
            mutate(child)
            new_pop.append(child)

        population = new_pop

    best = min(population, key=total_distance)
    return best, total_distance(best)

# -----------------------------
# PSO (Simplified for TSP)
# -----------------------------
def pso():
    num_particles = 30
    iterations = 50

    particles = [list(np.random.permutation(NUM_CITIES)) for _ in range(num_particles)]
    pbest = particles[:]
    gbest = min(particles, key=total_distance)

    for _ in range(iterations):
        for i in range(num_particles):
            if total_distance(particles[i]) < total_distance(pbest[i]):
                pbest[i] = particles[i][:]

            if total_distance(particles[i]) < total_distance(gbest):
                gbest = particles[i][:]

            # Swap towards best
            for _ in range(3):
                a, b = random.sample(range(NUM_CITIES), 2)
                particles[i][a], particles[i][b] = particles[i][b], particles[i][a]

    return gbest, total_distance(gbest)

# -----------------------------
# ANT COLONY OPTIMIZATION
# -----------------------------
def aco():
    ants = 40
    iterations = 80
    alpha = 1
    beta = 5
    evaporation = 0.1

    pheromone = np.ones((NUM_CITIES, NUM_CITIES))

    def probability(i, visited):
        probs = []
        for j in range(NUM_CITIES):
            if j in visited:
                probs.append(0)
            else:
                tau = pheromone[i][j] ** alpha
                eta = (1 / (distance(cities[i], cities[j]) + 1e-6)) ** beta
                probs.append(tau * eta)
        probs = np.array(probs)
        return probs / probs.sum()

    best_route = None
    best_dist = float('inf')

    for _ in range(iterations):
        all_routes = []

        for _ in range(ants):
            route = [random.randint(0, NUM_CITIES-1)]

            while len(route) < NUM_CITIES:
                probs = probability(route[-1], route)
                next_city = np.random.choice(range(NUM_CITIES), p=probs)
                route.append(next_city)

            dist = total_distance(route)
            all_routes.append((route, dist))

            if dist < best_dist:
                best_route, best_dist = route, dist

        pheromone *= (1 - evaporation)

        for route, dist in all_routes:
            for i in range(NUM_CITIES):
                a, b = route[i], route[(i+1)%NUM_CITIES]
                pheromone[a][b] += 1 / dist

    return best_route, best_dist

# -----------------------------
# RUN ALL
# -----------------------------
ga_route, ga_dist = genetic_algorithm()
pso_route, pso_dist = pso()
aco_route, aco_dist = aco()

print("\n--- RESULTS ---")
print("GA Distance:", ga_dist)
print("PSO Distance:", pso_dist)
print("ACO Distance:", aco_dist)

# -----------------------------
# Plot Best Route (ACO)
# -----------------------------
def plot_route(route, title):
    x = [cities[i][0] for i in route] + [cities[route[0]][0]]
    y = [cities[i][1] for i in route] + [cities[route[0]][1]]

    plt.plot(x, y, marker='o')
    plt.title(title)
    plt.show()

plot_route(aco_route, "Best Route (ACO)")